name: Create Release
run-name: ${{ github.actor }} is running release note

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 20

      - name: Synchronize Packages
        run: yarn

      - name: Update Main Branch
        run: git fetch origin main --unshallow

      - name: Create Release ( ${{ matrix.package }} )
        run: yarn md-automation -- --command create-release --packages ${{ matrix.package }} --since origin/main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
